use('Furniview');

db.Pagos.insertMany([
    {
        monto_total: 100.52,
        fecha_pago: null,
        metodo: 'Tarjeta de credito',
        estado: 'Pagado',
        referencia_pago: '1982387123',
        proveedor_pago: '',
        carrito: ObjectId(),
    },
    {
        monto_total: 200.12,
        fecha_pago: null,
        metodo: 'Tarjeta de debito',
        estado: 'Fallido',
        referencia_pago: '43845897345',
        proveedor_pago: '',
        carrito: ObjectId(),
    },
    {
        monto_total: 300.00,
        fecha_pago: null,
        metodo: 'Proveedor de pago',
        estado: 'Pendiente',
        referencia_pago: '923432974832',
        proveedor_pago: '',
        carrito: ObjectId(),
    },
    {
        monto_total: 400.00,
        fecha_pago: null,
        metodo: 'Tarjeta de debito',
        estado: 'Pagado',
        referencia_pago: '2093747882634',
        proveedor_pago: '',
        carrito: ObjectId(),
    },
    {
        monto_total: 5100.00,
        fecha_pago: null,
        metodo: 'Tarjeta de debito',
        estado: 'Fallido',
        referencia_pago: '02374612324',
        proveedor_pago: '',
        carrito: ObjectId(),
    },
    {
        monto_total: 600.00,
        fecha_pago: null,
        metodo: 'Tarjeta de debito',
        estado: 'Pendiente',
        referencia_pago: '29037672356',
        proveedor_pago: '',
        carrito: ObjectId(),
    },
    {
        monto_total: 700.00,
        fecha_pago: null,
        metodo: 'Tarjeta de debito',
        estado: 'Pagado',
        referencia_pago: '20384652388',
        proveedor_pago: '',
        carrito: ObjectId(),
    },
    {
        monto_total: 800.00,
        fecha_pago: null,
        metodo: 'Tarjeta de debito',
        estado: 'Fallido',
        referencia_pago: '09324978329847',
        proveedor_pago: '',
        carrito: ObjectId(),
    },
    {
        monto_total: 900.00,
        fecha_pago: null,
        metodo: 'Tarjeta de debito',
        estado: 'Pendiente',
        referencia_pago: '023984328492834',
        proveedor_pago: '',
        carrito: ObjectId(),
    },
    {
        monto_total: 1000.00,
        fecha_pago: null,
        metodo: 'Tarjeta de debito',
        estado: 'Pagado',
        referencia_pago: '2093483298463287',
        proveedor_pago: '',
        carrito: ObjectId(),
    },
])