use('Furniview');

db.Proveedores.insertMany([
    {
        nombre: 'Ludwig Ivan Ortiz Sierra',
        contacto_nombre: 'Ludwig Ivan',
        telefono: ['353-101-8343'],
        email: 'ivansierras11@gmail.com',
        contrasena: '123456789',
        direccion: {
            calle: 'Frank Moreno 4B',
            colonia: 'La Muda',
            ciudad: 'Sahuayo',
            estado: 'Michoacan',
            cp: '59023',
        },
        estado_proveedor: true,
        fecha_registro: new Date(),
        fecha_ultima_actualizacion: new Date(),
        website: 'https://github.com/Ludwig-Ivan',
        tipo: 'Fabricante',
    },
    {
        nombre: 'Sergio Octavio Cervantes Mujica',
        contacto_nombre: 'ElSeco',
        telefono: ['390-122-1232'],
        email: 'elseco12@gmail.com',
        contrasena: '123456789',
        direccion: {
            calle: 'Frank Esquino 4B',
            colonia: 'La Mocha',
            ciudad: 'Cojumatlan',
            estado: 'Michoacan',
            cp: '59013',
        },
        estado_proveedor: true,
        fecha_registro: new Date(),
        fecha_ultima_actualizacion: new Date(),
        website: 'https://github.com/',
        tipo: 'Mayorista',
    },
    {
        nombre: 'Daniel Villasenor',
        contacto_nombre: 'El Altisimo',
        telefono: ['564-234-1234'],
        email: 'villasenor@gmail.com',
        contrasena: '123456789',
        direccion: {
            calle: 'juarez 4B',
            colonia: 'Las Brisas',
            ciudad: 'Sahuayo',
            estado: 'Michoacan',
            cp: '59023',
        },
        estado_proveedor: true,
        fecha_registro: new Date(),
        fecha_ultima_actualizacion: new Date(),
        website: 'https://github.com/',
        tipo: 'Distribuidor',
    },
    {
        nombre: 'Jesus Alfonso Cuevas Avila',
        contacto_nombre: 'Poncho',
        telefono: ['938-234-234'],
        email: 'poncho@gmail.com',
        contrasena: '123456789',
        direccion: {
            calle: 'Luis antonio 15B',
            colonia: 'Las Brisas',
            ciudad: 'Sahuayo',
            estado: 'Michoacan',
            cp: '59023',
        },
        estado_proveedor: true,
        fecha_registro: new Date(),
        fecha_ultima_actualizacion: new Date(),
        website: 'https://github.com/',
        tipo: 'Mayorista',
    },
    {
        nombre: 'Emmanuel Saladana Alvarez',
        contacto_nombre: 'Manny',
        telefono: ['909-233-3423'],
        email: 'salem@gmail.com',
        contrasena: '123456789',
        direccion: {
            calle: 'sepacho 15B',
            colonia: 'Las risas',
            ciudad: 'tzitzuntzan',
            estado: 'Michoacan',
            cp: '59023',
        },
        estado_proveedor: true,
        fecha_registro: new Date(),
        fecha_ultima_actualizacion: new Date(),
        website: 'https://github.com/',
        tipo: 'Fabricante',
    },
])