use('Furniview');

db.Envios.insertMany([
    {
        fecha_envio: new Date(),
        fecha_entrega: null,
        estado: 'En transito',
        metodo: 'Estandar',
        costo: 200.00,
        numero_seguimiento: '19828737219873',
        peso: 150.45,
        dimensiones: '15m x 12m x 12m',
        intentos_entrega: 0,
        fecha_cancelacion: null,
        compania_transporte: 'Estafeta',
        carrito: ObjectId(),
        locacion: ObjectId(),
    },
    {
        fecha_envio: new Date(),
        fecha_entrega: null,
        estado: 'Entregado',
        metodo: 'Expreso',
        costo: 100.00,
        numero_seguimiento: '3456439873',
        peso: 150.45,
        dimensiones: '15m x 12m x 12m',
        intentos_entrega: 0,
        fecha_cancelacion: null,
        compania_transporte: 'Estafeta',
        carrito: ObjectId(),
        locacion: ObjectId(),
    },
    {
        fecha_envio: new Date(),
        fecha_entrega: null,
        estado: 'Pendiente',
        metodo: 'En tienda',
        costo: 100.00,
        numero_seguimiento: '198223432565873',
        peso: 150.45,
        dimensiones: '15m x 12m x 12m',
        intentos_entrega: 0,
        fecha_cancelacion: null,
        compania_transporte: 'Estafeta',
        carrito: ObjectId(),
        locacion: ObjectId(),
    },
    {
        fecha_envio: new Date(),
        fecha_entrega: null,
        estado: 'Entregado',
        metodo: 'Estandar',
        costo: 100.00,
        numero_seguimiento: '1345673459873',
        peso: 150.45,
        dimensiones: '15m x 12m x 12m',
        intentos_entrega: 0,
        fecha_cancelacion: null,
        compania_transporte: 'Estafeta',
        carrito: ObjectId(),
        locacion: ObjectId(),
    },
    {
        fecha_envio: new Date(),
        fecha_entrega: null,
        estado: 'Pendiente',
        metodo: 'En tienda',
        costo: 100.00,
        numero_seguimiento: '1934523473',
        peso: 150.45,
        dimensiones: '15m x 12m x 12m',
        intentos_entrega: 0,
        fecha_cancelacion: null,
        compania_transporte: 'Estafeta',
        carrito: ObjectId(),
        locacion: ObjectId(),
    },
    {
        fecha_envio: new Date(),
        fecha_entrega: null,
        estado: 'Entregado',
        metodo: 'Expreso',
        costo: 100.00,
        numero_seguimiento: '19897686873',
        peso: 150.45,
        dimensiones: '15m x 12m x 12m',
        intentos_entrega: 0,
        fecha_cancelacion: null,
        compania_transporte: 'Estafeta',
        carrito: ObjectId(),
        locacion: ObjectId(),
    },
    {
        fecha_envio: new Date(),
        fecha_entrega: null,
        estado: 'En transito',
        metodo: 'Estandar',
        costo: 100.00,
        numero_seguimiento: '198245678459873',
        peso: 150.45,
        dimensiones: '15m x 12m x 12m',
        intentos_entrega: 0,
        fecha_cancelacion: null,
        compania_transporte: 'Estafeta',
        carrito: ObjectId(),
        locacion: ObjectId(),
    },
    {
        fecha_envio: new Date(),
        fecha_entrega: null,
        estado: 'En transito',
        metodo: 'Estandar',
        costo: 100.00,
        numero_seguimiento: '198456745673',
        peso: 150.45,
        dimensiones: '15m x 12m x 12m',
        intentos_entrega: 0,
        fecha_cancelacion: null,
        compania_transporte: 'Estafeta',
        carrito: ObjectId(),
        locacion: ObjectId(),
    },
    {
        fecha_envio: new Date(),
        fecha_entrega: null,
        estado: 'En transito',
        metodo: 'Estandar',
        costo: 100.00,
        numero_seguimiento: '19456767639873',
        peso: 150.45,
        dimensiones: '15m x 12m x 12m',
        intentos_entrega: 0,
        fecha_cancelacion: null,
        compania_transporte: 'Estafeta',
        carrito: ObjectId(),
        locacion: ObjectId(),
    },
    {
        fecha_envio: new Date(),
        fecha_entrega: null,
        estado: 'En transito',
        metodo: 'Estandar',
        costo: 100.00,
        numero_seguimiento: '198282345234873',
        peso: 150.45,
        dimensiones: '15m x 12m x 12m',
        intentos_entrega: 0,
        fecha_cancelacion: null,
        compania_transporte: 'Estafeta',
        carrito: ObjectId(),
        locacion: ObjectId(),
    },
])