use('Furniview');
//? Registros Listos
db.Tickets_Soporte.insertMany([
    {
        _id: 1,
        fecha_creacion: new Date('2023-11-25 00:00:00'),
        estado: "Abierto",
        prioridad: "Alta",
        asunto: "Detalles con una compra no reflejada",
        descripcion: "El servidor por alguna razón no reflejó un pedido en mi plataforma",
        fecha_resolucion: new Date('2023-11-30 00:00:00'),
        resolucion: "",
        fecha_actualizacion: new Date('2023-11-30 00:00:00'),
        comentarios: "Verificar que el dispositivo usado debe estar con conexión a internet",
        adjuntos: "https:\/\/www.google.com\/",
        medio_contacto: "Chat",
        calificacion: 5,
        id_categoria_ticket: 1,
        id_usuario: 1
    },
    {
        _id: 2,
        fecha_creacion: new Date('2023-08-12 00:00:00'),
        estado: "Cerrado",
        prioridad: "Media",
        asunto: "Problema al cargar imágenes",
        descripcion: "Las imágenes no se cargan correctamente en la página de productos.",
        fecha_resolucion: new Date('2023-08-13 00:00:00'),
        resolucion: "",
        fecha_actualizacion: new Date('2023-08-13 00:00:00'),
        comentarios: "Revisar la conexión de internet y el tamaño de las imágenes",
        adjuntos: "https:\/\/www.imgur.com\/",
        medio_contacto: "Correo",
        calificacion: 4,
        id_categoria_ticket: 2,
        id_usuario: 2
    },
    {
        _id: 3,
        fecha_creacion: new Date('2023-05-14 00:00:00'),
        estado: "En Proceso",
        prioridad: "Baja",
        asunto: "Pregunta sobre un reembolso",
        descripcion: "El cliente quiere saber sobre el estado de su reembolso",
        resolucion: "",
        comentarios: "Pendiente de revisión del equipo de finanzas",
        medio_contacto: "Teléfono",
        calificacion: 3,
        id_categoria_ticket: 3,
        id_usuario: 3
    },
    {
        _id: 4,
        fecha_creacion: new Date('2023-10-02 00:00:00'),
        estado: "Abierto",
        prioridad: "Alta",
        asunto: "Pedido cancelado sin aviso",
        descripcion: "El pedido se canceló sin que el cliente fuera notificado",
        fecha_resolucion: new Date('2023-10-05 00:00:00'),
        resolucion: "",
        fecha_actualizacion: new Date('2023-10-05 00:00:00'),
        comentarios: "Ajustar notificaciones de cancelación automática",
        medio_contacto: "Chat",
        calificacion: 5,
        id_categoria_ticket: 4,
        id_usuario: 4
    },
    {
        _id: 5,
        fecha_creacion: new Date('2023-07-25 00:00:00'),
        estado: "Cerrado",
        prioridad: "Alta",
        asunto: "Factura no emitida correctamente",
        descripcion: "El sistema no generó la factura automáticamente",
        fecha_resolucion: new Date('2023-07-26 00:00:00'),
        resolucion: "",
        fecha_actualizacion: new Date('2023-07-26 00:00:00'),
        comentarios: "Confirmar emisión manual si el error persiste",
        adjuntos: "https:\/\/www.facturaejemplo.com\/",
        medio_contacto: "Correo",
        calificacion: 5,
        id_categoria_ticket: 1,
        id_usuario: 4
    },
    {
        _id: 6,
        fecha_creacion: new Date('2023-11-25 00:00:00'),
        estado: "Abierto",
        prioridad: "Alta",
        asunto: "Detalles con una compra no reflejada",
        descripcion: "El servidor por alguna razón no reflejó un pedido en mi plataforma",
        fecha_resolucion: new Date('2023-11-30 00:00:00'),
        resolucion: "",
        fecha_actualizacion: new Date('2023-11-30 00:00:00'),
        comentarios: "Verificar que el dispositivo usado debe estar con conexión a internet",
        adjuntos: "https:\/\/www.google.com\/",
        medio_contacto: "Chat",
        calificacion: 5,
        id_categoria_ticket: 1,
        id_usuario: 1
    },
    {
        _id: 7,
        fecha_creacion: new Date('2023-08-12 00:00:00'),
        estado: "Cerrado",
        prioridad: "Media",
        asunto: "Problema al cargar imágenes",
        descripcion: "Las imágenes no se cargan correctamente en la página de productos.",
        fecha_resolucion: new Date('2023-08-13 00:00:00'),
        resolucion: "",
        fecha_actualizacion: new Date('2023-08-13 00:00:00'),
        comentarios: "Revisar la conexión de internet y el tamaño de las imágenes",
        adjuntos: "https:\/\/www.imgur.com\/",
        medio_contacto: "Correo",
        calificacion: 4,
        id_categoria_ticket: 2,
        id_usuario: 2
    },
    {
        _id: 8,
        fecha_creacion: new Date('2023-05-14 00:00:00'),
        estado: "En Proceso",
        prioridad: "Baja",
        asunto: "Pregunta sobre un reembolso",
        descripcion: "El cliente quiere saber sobre el estado de su reembolso",
        resolucion: "",
        comentarios: "Pendiente de revisión del equipo de finanzas",
        medio_contacto: "Teléfono",
        calificacion: 3,
        id_categoria_ticket: 3,
        id_usuario: 3
    },
    {
        _id: 9,
        fecha_creacion: new Date('2023-10-02 00:00:00'),
        estado: "Abierto",
        prioridad: "Alta",
        asunto: "Pedido cancelado sin aviso",
        descripcion: "El pedido se canceló sin que el cliente fuera notificado",
        fecha_resolucion: new Date('2023-10-05 00:00:00'),
        resolucion: "",
        fecha_actualizacion: new Date('2023-10-05 00:00:00'),
        comentarios: "Ajustar notificaciones de cancelación automática",
        medio_contacto: "Chat",
        calificacion: 5,
        id_categoria_ticket: 4,
        id_usuario: 4
    },
    {
        _id: 10,
        fecha_creacion: new Date('2023-07-25 00:00:00'),
        estado: "Cerrado",
        prioridad: "Alta",
        asunto: "Factura no emitida correctamente",
        descripcion: "El sistema no generó la factura automáticamente",
        fecha_resolucion: new Date('2023-07-26 00:00:00'),
        resolucion: "",
        fecha_actualizacion: new Date('2023-07-26 00:00:00'),
        comentarios: "Confirmar emisión manual si el error persiste",
        adjuntos: "https:\/\/www.facturaejemplo.com\/",
        medio_contacto: "Correo",
        calificacion: 5,
        id_categoria_ticket: 1,
        id_usuario: 4
    },
    {
        _id: 11,
        fecha_creacion: new Date('2023-11-25 00:00:00'),
        estado: "Abierto",
        prioridad: "Alta",
        asunto: "Detalles con una compra no reflejada",
        descripcion: "El servidor por alguna razón no reflejó un pedido en mi plataforma",
        fecha_resolucion: new Date('2023-11-30 00:00:00'),
        resolucion: "",
        fecha_actualizacion: new Date('2023-11-30 00:00:00'),
        comentarios: "Verificar que el dispositivo usado debe estar con conexión a internet",
        adjuntos: "https:\/\/www.google.com\/",
        medio_contacto: "Chat",
        calificacion: 5,
        id_categoria_ticket: 1,
        id_usuario: 1
    },
    {
        _id: 12,
        fecha_creacion: new Date('2023-08-12 00:00:00'),
        estado: "Cerrado",
        prioridad: "Media",
        asunto: "Problema al cargar imágenes",
        descripcion: "Las imágenes no se cargan correctamente en la página de productos.",
        fecha_resolucion: new Date('2023-08-13 00:00:00'),
        resolucion: "",
        fecha_actualizacion: new Date('2023-08-13 00:00:00'),
        comentarios: "Revisar la conexión de internet y el tamaño de las imágenes",
        adjuntos: "https:\/\/www.imgur.com\/",
        medio_contacto: "Correo",
        calificacion: 4,
        id_categoria_ticket: 2,
        id_usuario: 2
    },
    {
        _id: 13,
        fecha_creacion: new Date('2023-05-14 00:00:00'),
        estado: "En Proceso",
        prioridad: "Baja",
        asunto: "Pregunta sobre un reembolso",
        descripcion: "El cliente quiere saber sobre el estado de su reembolso",
        resolucion: "",
        comentarios: "Pendiente de revisión del equipo de finanzas",
        medio_contacto: "Teléfono",
        calificacion: 3,
        id_categoria_ticket: 3,
        id_usuario: 3
    },
    {
        _id: 14,
        fecha_creacion: new Date('2023-10-02 00:00:00'),
        estado: "Abierto",
        prioridad: "Alta",
        asunto: "Pedido cancelado sin aviso",
        descripcion: "El pedido se canceló sin que el cliente fuera notificado",
        fecha_resolucion: new Date('2023-10-05 00:00:00'),
        resolucion: "",
        fecha_actualizacion: new Date('2023-10-05 00:00:00'),
        comentarios: "Ajustar notificaciones de cancelación automática",
        medio_contacto: "Chat",
        calificacion: 5,
        id_categoria_ticket: 4,
        id_usuario: 4
    },
    {
        _id: 15,
        fecha_creacion: new Date('2023-07-25 00:00:00'),
        estado: "Cerrado",
        prioridad: "Alta",
        asunto: "Factura no emitida correctamente",
        descripcion: "El sistema no generó la factura automáticamente",
        fecha_resolucion: new Date('2023-07-26 00:00:00'),
        resolucion: "",
        fecha_actualizacion: new Date('2023-07-26 00:00:00'),
        comentarios: "Confirmar emisión manual si el error persiste",
        adjuntos: "https:\/\/www.facturaejemplo.com\/",
        medio_contacto: "Correo",
        calificacion: 5,
        id_categoria_ticket: 1,
        id_usuario: 4
    },
    {
        _id: 16,
        fecha_creacion: new Date('2023-11-25 00:00:00'),
        estado: "Abierto",
        prioridad: "Alta",
        asunto: "Detalles con una compra no reflejada",
        descripcion: "El servidor por alguna razón no reflejó un pedido en mi plataforma",
        fecha_resolucion: new Date('2023-11-30 00:00:00'),
        resolucion: "",
        fecha_actualizacion: new Date('2023-11-30 00:00:00'),
        comentarios: "Verificar que el dispositivo usado debe estar con conexión a internet",
        adjuntos: "https:\/\/www.google.com\/",
        medio_contacto: "Chat",
        calificacion: 5,
        id_categoria_ticket: 1,
        id_usuario: 1
    },
    {
        _id: 17,
        fecha_creacion: new Date('2023-08-12 00:00:00'),
        estado: "Cerrado",
        prioridad: "Media",
        asunto: "Problema al cargar imágenes",
        descripcion: "Las imágenes no se cargan correctamente en la página de productos.",
        fecha_resolucion: new Date('2023-08-13 00:00:00'),
        resolucion: "",
        fecha_actualizacion: new Date('2023-08-13 00:00:00'),
        comentarios: "Revisar la conexión de internet y el tamaño de las imágenes",
        adjuntos: "https:\/\/www.imgur.com\/",
        medio_contacto: "Correo",
        calificacion: 4,
        id_categoria_ticket: 2,
        id_usuario: 2
    },
    {
        _id: 18,
        fecha_creacion: new Date('2023-05-14 00:00:00'),
        estado: "En Proceso",
        prioridad: "Baja",
        asunto: "Pregunta sobre un reembolso",
        descripcion: "El cliente quiere saber sobre el estado de su reembolso",
        resolucion: "",
        comentarios: "Pendiente de revisión del equipo de finanzas",
        medio_contacto: "Teléfono",
        calificacion: 3,
        id_categoria_ticket: 3,
        id_usuario: 3
    },
    {
        _id: 19,
        fecha_creacion: new Date('2023-10-02 00:00:00'),
        estado: "Abierto",
        prioridad: "Alta",
        asunto: "Pedido cancelado sin aviso",
        descripcion: "El pedido se canceló sin que el cliente fuera notificado",
        fecha_resolucion: new Date('2023-10-05 00:00:00'),
        resolucion: "",
        fecha_actualizacion: new Date('2023-10-05 00:00:00'),
        comentarios: "Ajustar notificaciones de cancelación automática",
        medio_contacto: "Chat",
        calificacion: 5,
        id_categoria_ticket: 4,
        id_usuario: 4
    },
    {
        _id: 20,
        fecha_creacion: new Date('2023-07-25 00:00:00'),
        estado: "Cerrado",
        prioridad: "Alta",
        asunto: "Factura no emitida correctamente",
        descripcion: "El sistema no generó la factura automáticamente",
        fecha_resolucion: new Date('2023-07-26 00:00:00'),
        resolucion: "",
        fecha_actualizacion: new Date('2023-07-26 00:00:00'),
        comentarios: "Confirmar emisión manual si el error persiste",
        adjuntos: "https:\/\/www.facturaejemplo.com\/",
        medio_contacto: "Correo",
        calificacion: 5,
        id_categoria_ticket: 1,
        id_usuario: 4
    }
]);