use('Furniview');
//? Registros de Usuarios Listos
db.Ofertas.insertMany([
  {
    _id: 1,
    nombre: "Descuento de Verano",
    descripcion: "Aprovecha un 15% de descuento en productos seleccionados.",
    tipo: "Porcentual",
    valor: 0.15,
    fecha_inicio: new Date('2023-11-15 00:00:00'),
    fecha_fin: new Date('2023-11-30 00:00:00'),
    estado: "Activa",
    codigo_promocional: "VERANO2024",
    condiciones_aplicacion: "Válido en compras superiores a $500.",
    limite_uso: 100,
    usos_actuales: 25,
    id_producto: 1,
    id_categoria: 1,
    id_usuario: 1,
    id_proveedor: 1
  },
  {
    _id: 2,
    nombre: "Oferta de Lanzamiento",
    descripcion: "Descuento de $500 en el lanzamiento de nuevos productos.",
    tipo: "Cantidad fija",
    valor: 500.00,
    fecha_inicio: new Date('2023-11-15 00:00:00'),
    fecha_fin: new Date('2023-11-30 00:00:00'),
    estado: "Activa",
    codigo_promocional: "LANZAMIENTO2024",
    condiciones_aplicacion: "Disponible para los primeros 50 clientes.",
    limite_uso: 50,
    usos_actuales: 10,
    id_producto: 2,
    id_categoria: 2,
    id_usuario: 2,
    id_proveedor: 2
  },
  {
    _id: 3,
    nombre: "Descuento de Fin de Año",
    descripcion: "Obtén un 20% de descuento en todos los productos.",
    tipo: "Porcentual",
    valor: 0.20,
    fecha_inicio: new Date('2024-08-31 00:00:00'),
    fecha_fin: new Date('2024-08-31 00:00:00'),
    estado: "Activa",
    codigo_promocional: "FINDEANO2024",
    condiciones_aplicacion: "Aplicable en todos los productos sin excepción.",
    limite_uso: 200,
    usos_actuales: 50,
    id_producto: 3,
    id_categoria: 3,
    id_usuario: 3,
    id_proveedor: 3
  },
  {
    _id: 4,
    nombre: "Descuento de Verano",
    descripcion: "Aprovecha un 15% de descuento en productos seleccionados.",
    tipo: "Porcentual",
    valor: 0.15,
    fecha_inicio: new Date('2023-11-15 00:00:00'),
    fecha_fin: new Date('2023-11-30 00:00:00'),
    estado: "Activa",
    codigo_promocional: "VERANO2024",
    condiciones_aplicacion: "Válido en compras superiores a $500.",
    limite_uso: 100,
    usos_actuales: 25,
    id_producto: 4,
    id_categoria: 4,
    id_usuario: 4,
    id_proveedor: 4
  },
  {
    _id: 5,
    nombre: "Oferta de Lanzamiento",
    descripcion: "Descuento de $500 en el lanzamiento de nuevos productos.",
    tipo: "Cantidad fija",
    valor: 500.00,
    fecha_inicio: new Date('2023-11-15 00:00:00'),
    fecha_fin: new Date('2023-11-30 00:00:00'),
    estado: "Activa",
    codigo_promocional: "LANZAMIENTO2024",
    condiciones_aplicacion: "Disponible para los primeros 50 clientes.",
    limite_uso: 50,
    usos_actuales: 10,
    id_producto: 5,
    id_categoria: 5,
    id_usuario: 5,
    id_proveedor: 5
  },
  {
    _id: 6,
    nombre: "Descuento de Verano",
    descripcion: "Aprovecha un 15% de descuento en productos seleccionados.",
    tipo: "Porcentual",
    valor: 0.15,
    fecha_inicio: new Date('2023-11-15 00:00:00'),
    fecha_fin: new Date('2023-11-30 00:00:00'),
    estado: "Activa",
    codigo_promocional: "VERANO2024",
    condiciones_aplicacion: "Válido en compras superiores a $500.",
    limite_uso: 100,
    usos_actuales: 25,
    id_producto: 6,
    id_categoria: 1,
    id_usuario: 1,
    id_proveedor: 1
  },
  {
    _id: 7,
    nombre: "Oferta de Lanzamiento",
    descripcion: "Descuento de $500 en el lanzamiento de nuevos productos.",
    tipo: "Cantidad fija",
    valor: 500.00,
    fecha_inicio: new Date('2023-11-15 00:00:00'),
    fecha_fin: new Date('2023-11-30 00:00:00'),
    estado: "Activa",
    codigo_promocional: "LANZAMIENTO2024",
    condiciones_aplicacion: "Disponible para los primeros 50 clientes.",
    limite_uso: 50,
    usos_actuales: 10,
    id_producto: 7,
    id_categoria: 2,
    id_usuario: 2,
    id_proveedor: 2
  },
  {
    _id: 8,
    nombre: "Descuento de Fin de Año",
    descripcion: "Obtén un 20% de descuento en todos los productos.",
    tipo: "Porcentual",
    valor: 0.20,
    fecha_inicio: new Date('2024-08-31 00:00:00'),
    fecha_fin: new Date('2024-08-31 00:00:00'),
    estado: "Activa",
    codigo_promocional: "FINDEANO2024",
    condiciones_aplicacion: "Aplicable en todos los productos sin excepción.",
    limite_uso: 200,
    usos_actuales: 50,
    id_producto: 8,
    id_categoria: 3,
    id_usuario: 3,
    id_proveedor: 3
  },
  {
    _id: 9,
    nombre: "Descuento de Verano",
    descripcion: "Aprovecha un 15% de descuento en productos seleccionados.",
    tipo: "Porcentual",
    valor: 0.15,
    fecha_inicio: new Date('2023-11-15 00:00:00'),
    fecha_fin: new Date('2023-11-30 00:00:00'),
    estado: "Activa",
    codigo_promocional: "VERANO2024",
    condiciones_aplicacion: "Válido en compras superiores a $500.",
    limite_uso: 100,
    usos_actuales: 25,
    id_producto: 9,
    id_categoria: 4,
    id_usuario: 4,
    id_proveedor: 4
  },
  {
    _id: 10,
    nombre: "Oferta de Lanzamiento",
    descripcion: "Descuento de $500 en el lanzamiento de nuevos productos.",
    tipo: "Cantidad fija",
    valor: 500.00,
    fecha_inicio: new Date('2023-11-15 00:00:00'),
    fecha_fin: new Date('2023-11-30 00:00:00'),
    estado: "Activa",
    codigo_promocional: "LANZAMIENTO2024",
    condiciones_aplicacion: "Disponible para los primeros 50 clientes.",
    limite_uso: 50,
    usos_actuales: 10,
    id_producto: 10,
    id_categoria: 5,
    id_usuario: 5,
    id_proveedor: 5
  },
  {
    _id: 11,
    nombre: "Descuento de Verano",
    descripcion: "Aprovecha un 15% de descuento en productos seleccionados.",
    tipo: "Porcentual",
    valor: 0.15,
    fecha_inicio: new Date('2023-11-15 00:00:00'),
    fecha_fin: new Date('2023-11-30 00:00:00'),
    estado: "Activa",
    codigo_promocional: "VERANO2024",
    condiciones_aplicacion: "Válido en compras superiores a $500.",
    limite_uso: 100,
    usos_actuales: 25,
    id_producto: 11,
    id_categoria: 1,
    id_usuario: 1,
    id_proveedor: 1
  },
  {
    _id: 12,
    nombre: "Oferta de Lanzamiento",
    descripcion: "Descuento de $500 en el lanzamiento de nuevos productos.",
    tipo: "Cantidad fija",
    valor: 500.00,
    fecha_inicio: new Date('2023-11-15 00:00:00'),
    fecha_fin: new Date('2023-11-30 00:00:00'),
    estado: "Activa",
    codigo_promocional: "LANZAMIENTO2024",
    condiciones_aplicacion: "Disponible para los primeros 50 clientes.",
    limite_uso: 50,
    usos_actuales: 10,
    id_producto: 12,
    id_categoria: 2,
    id_usuario: 2,
    id_proveedor: 2
  },
  {
    _id: 13,
    nombre: "Descuento de Fin de Año",
    descripcion: "Obtén un 20% de descuento en todos los productos.",
    tipo: "Porcentual",
    valor: 0.20,
    fecha_inicio: new Date('2024-08-31 00:00:00'),
    fecha_fin: new Date('2024-08-31 00:00:00'),
    estado: "Activa",
    codigo_promocional: "FINDEANO2024",
    condiciones_aplicacion: "Aplicable en todos los productos sin excepción.",
    limite_uso: 200,
    usos_actuales: 50,
    id_producto: 13,
    id_categoria: 3,
    id_usuario: 3,
    id_proveedor: 3
  },
  {
    _id: 14,
    nombre: "Descuento de Verano",
    descripcion: "Aprovecha un 15% de descuento en productos seleccionados.",
    tipo: "Porcentual",
    valor: 0.15,
    fecha_inicio: new Date('2023-11-15 00:00:00'),
    fecha_fin: new Date('2023-11-30 00:00:00'),
    estado: "Activa",
    codigo_promocional: "VERANO2024",
    condiciones_aplicacion: "Válido en compras superiores a $500.",
    limite_uso: 100,
    usos_actuales: 25,
    id_producto: 14,
    id_categoria: 4,
    id_usuario: 4,
    id_proveedor: 4
  },
  {
    _id: 15,
    nombre: "Oferta de Lanzamiento",
    descripcion: "Descuento de $500 en el lanzamiento de nuevos productos.",
    tipo: "Cantidad fija",
    valor: 500.00,
    fecha_inicio: new Date('2023-11-15 00:00:00'),
    fecha_fin: new Date('2023-11-30 00:00:00'),
    estado: "Activa",
    codigo_promocional: "LANZAMIENTO2024",
    condiciones_aplicacion: "Disponible para los primeros 50 clientes.",
    limite_uso: 50,
    usos_actuales: 10,
    id_producto: 15,
    id_categoria: 5,
    id_usuario: 5,
    id_proveedor: 5
  },
  {
    _id: 16,
    nombre: "Descuento de Verano",
    descripcion: "Aprovecha un 15% de descuento en productos seleccionados.",
    tipo: "Porcentual",
    valor: 0.15,
    fecha_inicio: new Date('2023-11-15 00:00:00'),
    fecha_fin: new Date('2023-11-30 00:00:00'),
    estado: "Activa",
    codigo_promocional: "VERANO2024",
    condiciones_aplicacion: "Válido en compras superiores a $500.",
    limite_uso: 100,
    usos_actuales: 25,
    id_producto: 16,
    id_categoria: 1,
    id_usuario: 1,
    id_proveedor: 1
  },
  {
    _id: 17,
    nombre: "Oferta de Lanzamiento",
    descripcion: "Descuento de $500 en el lanzamiento de nuevos productos.",
    tipo: "Cantidad fija",
    valor: 500.00,
    fecha_inicio: new Date('2023-11-15 00:00:00'),
    fecha_fin: new Date('2023-11-30 00:00:00'),
    estado: "Activa",
    codigo_promocional: "LANZAMIENTO2024",
    condiciones_aplicacion: "Disponible para los primeros 50 clientes.",
    limite_uso: 50,
    usos_actuales: 10,
    id_producto: 17,
    id_categoria: 2,
    id_usuario: 2,
    id_proveedor: 2
  },
  {
    _id: 18,
    nombre: "Descuento de Fin de Año",
    descripcion: "Obtén un 20% de descuento en todos los productos.",
    tipo: "Porcentual",
    valor: 0.20,
    fecha_inicio: new Date('2024-08-31 00:00:00'),
    fecha_fin: new Date('2024-08-31 00:00:00'),
    estado: "Activa",
    codigo_promocional: "FINDEANO2024",
    condiciones_aplicacion: "Aplicable en todos los productos sin excepción.",
    limite_uso: 200,
    usos_actuales: 50,
    id_producto: 18,
    id_categoria: 3,
    id_usuario: 3,
    id_proveedor: 3
  },
  {
    _id: 19,
    nombre: "Descuento de Verano",
    descripcion: "Aprovecha un 15% de descuento en productos seleccionados.",
    tipo: "Porcentual",
    valor: 0.15,
    fecha_inicio: new Date('2023-11-15 00:00:00'),
    fecha_fin: new Date('2023-11-30 00:00:00'),
    estado: "Activa",
    codigo_promocional: "VERANO2024",
    condiciones_aplicacion: "Válido en compras superiores a $500.",
    limite_uso: 100,
    usos_actuales: 25,
    id_producto: 19,
    id_categoria: 4,
    id_usuario: 4,
    id_proveedor: 4
  },
  {
    _id: 20,
    nombre: "Oferta de Lanzamiento",
    descripcion: "Descuento de $500 en el lanzamiento de nuevos productos.",
    tipo: "Cantidad fija",
    valor: 500.00,
    fecha_inicio: new Date('2023-11-15 00:00:00'),
    fecha_fin: new Date('2023-11-30 00:00:00'),
    estado: "Activa",
    codigo_promocional: "LANZAMIENTO2024",
    condiciones_aplicacion: "Disponible para los primeros 50 clientes.",
    limite_uso: 50,
    usos_actuales: 10,
    id_producto: 20,
    id_categoria: 5,
    id_usuario: 5,
    id_proveedor: 5
  }
]);